---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Déploie une instance EC2 dans la région spécifiée"

Parameters:
  RegionAMI:
    Type: String
    Description: "AMI spécifique à la région"
  InstanceName:
    Type: String
    Default: "MultiRegionInstance"
    Description: "Nom de l'instance EC2"

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:!Ref RegionAMI
      InstanceType: t3.micro
      Tags:
        - Key: Name
          Value:!Ref InstanceName
